EscPc/EscPc/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from EscPc.quickstart import views
from rest_framework import routers

#API
router = routers.DefaultRouter()
router.register(r'motherboard', views.PlacasMadreViewSet)
router.register(r'processor', views.ProcesadorViewSet)
router.register(r'gpu', views.GpuViewSet)
router.register(r'memorias-ram', views.RamViewSet)
router.register(r'users', views.UserViewSet)

urlpatterns = [
   path('admin/', admin.site.urls),
   path('', include('catalog.urls')),
   path('accounts/', include('django.contrib.auth.urls')),
   path('accounts/', include('sesion.urls')),
   path('cart/', include('cart.urls')),
   path('', include(router.urls)),
   path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

if settings.DEBUG:  
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

EscPc/cart/urls.py
from django.urls import path
from .views import *

app_name = "cart"

urlpatterns = [
   path('add_product/<int:product_id>/', add_product, name='add_product'),
   path('remove_product/<int:product_id>/', remove_product, name='remove_product'),
   path('decrement_product/<int:product_id>/', decrement_product, name='decrement_product'),
   path('clear/', clear_cart, name='clear_cart'),
   
   path('add_procesador/<int:product_id>/', add_procesador, name='add_procesador'),
   path('remove_procesador/<int:product_id>/', remove_procesador, name='remove_procesador'),
   path('decrement_procesador/<int:product_id>/', decrement_procesador, name='decrement_procesador'),
   path('clear_procesador/', clear_cart_procesador, name='clear_cart_procesador'),
   
   path('add_gpu/<int:product_id>/', add_gpu, name='add_gpu'),
   path('remove_gpu/<int:product_id>/', remove_gpu, name='remove_gpu'),
   path('decrement_gpu/<int:product_id>/', decrement_gpu, name='decrement_gpu'),
   path('clear_gpu/', clear_cart_gpu, name='clear_cart_gpu'),
   
   path('add_ram/<int:product_id>/', add_ram, name='add_ram'),
   path('remove_ram/<int:product_id>/', remove_ram, name='remove_ram'),
   path('decrement_ram/<int:product_id>/', decrement_ram, name='decrement_ram'),
   path('clear_ram/', clear_cart_ram, name='clear_cart_ram'),
   
]

EscPc/catalog/urls.py
#!/usr/bin/python3
from django.urls import path, include
from . import views

'''
      AQUI SE ENCUENTRAN LAS URLS DE LOS PRODUCTOS, TANTO LISTAS COMO
      LOS DEL CRUD, INDICANDO COMO PRIMER PARAMETRO EL URL QUE SE BUSCARA,
      COMO SEGUNDO, LA VISTA DE DONDE SE SACARA LA INFO Y COMO TERCER PARA-
      METRO, UN NOMBRE PARA PODER LLAMAR A LA URL DESDE OTRA PESTANNIA
   '''

urlpatterns = [
   
   #API
   
   
   # URL PRINCIPALES
   path('home', views.index, name="index"),
   path('placasmadres/', views.placamadre, name="placamadre"),
   path('procesadores/', views.procesador, name="procesador"),
   path('tarjetadevideo/', views.video, name="video"),
   path('ram/', views.rams, name="rams"),
   path('almacenamiento/', views.alma, name="alma"),
   path('fuenteDePoder/', views.fuente, name="fuente"),
   path('gabinetes/', views.gabo, name="gabo"),
   path('monitores/', views.moni, name="moni"),
   path('contacto/', views.contacto, name="contacto"),


   # URL PLACAS MADRE
   path('placasmadre/', views.PlacaListView.as_view(), name="placas"),
   path('placamadre/<int:pk>', views.PlacaDetailView.as_view(), name="placas-detail"),
   path('nueva-placa/', views.nueva_placa, name="nueva_placa"),
   path('modificar-placa/<id>/', views.modificar_placa, name="modificar_placa"),
   path('eliminar-placa/<id>/', views.eliminar_placa, name="eliminar_placa"),

   # URL PROCESADORES
   path('procesadore/', views.ProceListView.as_view(), name="procesadores"),
   path('procesador/<int:pk>', views.ProceDetailView.as_view(), name="procesadores-detail"),
   path('nuevo-procesador/', views.nuevo_procesador, name="nuevo_procesador"),
   path('modificar-procesador/<id>/', views.modicar_procesador, name="modificar_procesador"),
   path('eliminar-procesador/<id>/', views.eliminar_procesador, name="eliminar_procesador"),

   # URL GPU'S
   path('gpus/', views.GpuListView.as_view(), name="gpus"),
   path('gpu/<int:pk>', views.GpuDetailView.as_view(), name="gpu-detail"),
   path('nueva-gpu/', views.nuevo_gpu, name="nueva_gpu"),
   path('modificar-gpu/<id>/', views.modificar_gpu, name="modificar_gpu"),
   path('eliminar-gpu/<id>/', views.eliminar_gpu, name="eliminar_gpu"),

   # URL RAM
   path('rams/', views.RamListView.as_view(), name="memoriasram"),
   path('ram/<int:pk>', views.RamDetailView.as_view(), name="ram-detail"),
   path('nueva-ram/', views.nueva_ram, name="nueva_ram"),
   path('modificar-ram/<id>/', views.modificar_ram, name="modificar_ram"),
   path('eliminar-ram/<id>/', views.eliminar_ram, name="eliminar_ram"),

   # URL ALMACENAMIENTOS
   path('almacenamientos/', views.AlmacenamientoListView.as_view(), name="almacenamientos"),
   path('almacenamiento/<int:pk>', views.AlmacenamientoDetailView.as_view(), name="almacenamiento-detail"),
   path('nuevo-almacenamiento/', views.nuevo_almacenamiento, name="nuevo_almacenamiento"),
   path('modificar-almacenamiento/<id>/', views.modificar_almacenamiento, name="modificar_almacenamiento"),
   path('eliminar-almacenamiento/<id>/', views.eliminar_almacenamiento, name="eliminar_almacenamiento"),

   # URL FUENTES DE PODER
   path('fuentes/', views.FuentesPoderListView.as_view(), name="fuentes"),
   path('fuente-poder/<int:pk>', views.FuentesPoderDetailView.as_view(), name="fuente-detail"),
   path('nueva-fuente/', views.nueva_fuente, name="nueva_fuente"),
   path('modificar-fuente/<id>/', views.modificar_fuente, name="modificar_fuente"),
   path('eliminar-fuente/<id>/', views.eliminar_fuente, name="eliminar_fuente"),

   # URL GABINETE
   path('gabinetes/', views.GabineteListView.as_view(), name="gabinetes"),
   path('gabinete/<int:pk>', views.GabineteDetailView.as_view(), name="gabinete-detail"),
   path('nuevo-gabinete/', views.nuevo_gabinete, name="nuevo_gabinete"),
   path('modificar-gabinete/<id>/', views.modificar_gabinete, name="modificar_gabinete"),
   path('eliminar-gabinete/<id>/', views.eliminar_gabinete, name="eliminar_gabinete"),

   #URL MONITOR
   path('monitores/', views.MonitoreListView.as_view(), name="monitores"),
   path('monitor/<int:pk>', views.MonitoreDetailView.as_view(), name="monitor-detail"),
   path('nuevo-monitor/', views.nuevo_monitor, name="nuevo_monitor"),
   path('modificar-monitor/<id>', views.modificar_monitor, name="modificar_monitor"),
   path('eliminar-monitor/<id>', views.eliminar_monitor, name="eliminar_monitor"),
   
   
   
]

EscPc/cart/models.py
from django.db import models
# Create your models here.

EscPc/catalog/forms.py
#!/usr/bin/python3
from django import forms
from django.forms import ModelForm
from .models import PlacasMadre, Procesadore, Gpu, Ram, Almacenamiento, FuentesPoder, Gabinete, Monitore, Contacto


'''
   AQUI SE ENCUENTRAN LOS FORMULARIOS QUE SE OCUPARAN, EN ESTE CASO ESTAMOS 
   EXTRAYENDO TODOS LOS CAMPOS DE CADA MODELO RESPECTIVAMENTE
'''


class PlacaForm(ModelForm):
   class Meta:
      model = PlacasMadre
      fields = '__all__'

class ProceForm(ModelForm):

   class Meta:
      model = Procesadore
      fields = '__all__'

class GpuForm(ModelForm):

   class Meta:
      model = Gpu
      fields = '__all__'

class RamForm(ModelForm):

   class Meta:
      model = Ram
      fields = '__all__'

class AlmacenamientoForm(ModelForm):

   class Meta:
      model = Almacenamiento
      fields = '__all__'

class FuentesPoderForm(ModelForm):

   class Meta:
      model = FuentesPoder
      fields = '__all__'

class GabineteForm(ModelForm):

   class Meta:
      model = Gabinete
      fields = '__all__'

class MonitoreForm(ModelForm):

   class Meta:
      model = Monitore
      fields = '__all__'

class ContactoForm(ModelForm):
   
   class Meta:
      model = Contacto
      fields = '__all__'
      

EscPc/cart/views.py
from django.shortcuts import redirect
from catalog.models import PlacasMadre, Procesadore, Gpu, Ram
from django.contrib.auth.decorators import login_required
from .cart import Cart

# Create your views here.
@login_required(login_url="/registration/login")
def add_product(request, product_id):
   cart = Cart(request)
   product = PlacasMadre.objects.get(id=product_id)
   cart.add(product=product)
   return redirect("placamadre")

@login_required(login_url="/registration/login")
def remove_product(request, product_id):
   cart = Cart(request)
   product = PlacasMadre.objects.get(id=product_id)
   cart.remove(product)
   return redirect("placamadre")

@login_required(login_url="/registration/login")
def decrement_product(request, product_id):
   cart = Cart(request)
   product = PlacasMadre.objects.get(id=product_id)
   cart.decrement(product=product)
   return redirect("placamadre")

@login_required(login_url="/registration/login")
def clear_cart(request):
   cart = Cart(request)
   cart.clear()
   return redirect("placamadre")



# PROCESADOR
@login_required(login_url="/registration/login")
def add_procesador(request, product_id):
   cart = Cart(request)
   product = Procesadore.objects.get(id=product_id)
   cart.add(product=product)
   return redirect("procesador")

@login_required(login_url="/registration/login")
def remove_procesador(request, product_id):
   cart = Cart(request)
   product = Procesadore.objects.get(id=product_id)
   cart.remove(product)
   return redirect("procesador")

@login_required(login_url="/registration/login")
def decrement_procesador(request, product_id):
   cart = Cart(request)
   product = Procesadore.objects.get(id=product_id)
   cart.decrement(product=product)
   return redirect("procesador")

@login_required(login_url="/registration/login")
def clear_cart_procesador(request):
   cart = Cart(request)
   cart.clear()
   return redirect("procesador")

# GPU

@login_required(login_url="/registration/login")
def add_gpu(request, product_id):
   cart = Cart(request)
   product = Gpu.objects.get(id=product_id)
   cart.add(product=product)
   return redirect("video")

@login_required(login_url="/registration/login")
def remove_gpu(request, product_id):
   cart = Cart(request)
   product = Gpu.objects.get(id=product_id)
   cart.remove(product)
   return redirect("video")

@login_required(login_url="/registration/login")
def decrement_gpu(request, product_id):
   cart = Cart(request)
   product = Gpu.objects.get(id=product_id)
   cart.decrement(product=product)
   return redirect("video")

@login_required(login_url="/registration/login")
def clear_cart_gpu(request):
   cart = Cart(request)
   cart.clear()
   return redirect("video")

# RAM
@login_required(login_url="/registration/login")
def add_ram(request, product_id):
   cart = Cart(request)
   product = Ram.objects.get(id=product_id)
   cart.add(product=product)
   return redirect("rams")

@login_required(login_url="/registration/login")
def remove_ram(request, product_id):
   cart = Cart(request)
   product = Ram.objects.get(id=product_id)
   cart.remove(product)
   return redirect("rams")

@login_required(login_url="/registration/login")
def decrement_ram(request, product_id):
   cart = Cart(request)
   product = Ram.objects.get(id=product_id)
   cart.decrement(product=product)
   return redirect("rams")

@login_required(login_url="/registration/login")
def clear_cart_ram(request):
   cart = Cart(request)
   cart.clear()
   return redirect("rams")

EscPc/catalog/templates/cart/widget.html
{% load cart_tags %}
<table class="table table-bordered">
   <thead>
      <tr>
         <th colspan="3" class="text-center">
            Carrito de Compras
         </th>
      </tr>
      <tr>
         <th>Marca</th>
         <th>Cantidad</th>
         <th>Opciones</th>
      </tr>
   </thead>
   <tbody>
      {% if request.session.cart.items %}
         {% for key, value in request.session.cart.items %}
            <tr class="text-center">
               <td>{{ value.name }}</td>
               <td>{{ value.quantity }}</td>
               <td>
                  {% block add_decrement %}
                  <a href="{% url 'cart:add_product' value.product_id %}"
                     class="btn btn-sm btn-success">
                     +
                  </a>
                  <a href="{% url 'cart:decrement_product' value.product_id %}"
                     class="ml-2 btn-sm btn btn-danger">
                     -
                  </a>
                  {% endblock %}
                  <hr>
                  Total {{ value.price|multiply:value.quantity|money_format:"$" }}
               </td>
            
            </tr>
         {% endfor %}
      
      {% else %}
         <tr>
            <td colspan="3">
               <div class="alert alert-danger text-center">
                  No tienes productos en el carrito
               </div>
            </td>
         </tr>
      {% endif %}
   </tbody>
   <tfoot>
      <tr>
         <td colspan="3">
            Total: {{ cart_total_amount|money_format:"$"}}
         </td>
      </tr>
   </tfoot>
</table>

EscPc/catalog/templates/cart/widget_gpu.html
{% load cart_tags %}
<table class="table table-bordered">
   <thead>
      <tr>
         <th colspan="3" class="text-center">
            Carrito de Compras
         </th>
      </tr>
      <tr>
         <th>Marca</th>
         <th>Cantidad</th>
         <th>Opciones</th>
      </tr>
   </thead>
   <tbody>
      {% if request.session.cart.items %}
         {% for key, value in request.session.cart.items %}
            <tr class="text-center">
               <td>{{ value.name }}</td>
               <td>{{ value.quantity }}</td>
               <td>
                  {% block add_decrement %}
                  <a href="{% url 'cart:add_gpu' value.product_id %}"
                     class="btn btn-sm btn-success">
                     +
                  </a>
                  <a href="{% url 'cart:decrement_gpu' value.product_id %}"
                     class="ml-2 btn-sm btn btn-danger">
                     -
                  </a>
                  {% endblock %}
                  <hr>
                  Total {{ value.price|multiply:value.quantity|money_format:"$" }}
               </td>
            
            </tr>
         {% endfor %}
      
      {% else %}
         <tr>
            <td colspan="3">
               <div class="alert alert-danger text-center">
                  No tienes productos en el carrito
               </div>
            </td>
         </tr>
      {% endif %}
   </tbody>
   <tfoot>
      <tr>
         <td colspan="3">
            Total: {{ cart_total_amount|money_format:"$"}}
         </td>
      </tr>
   </tfoot>
</table>

EscPc/catalog/templates/cart/widget_procesador.html
{% load cart_tags %}
<table class="table table-bordered">
   <thead>
      <tr>
         <th colspan="3" class="text-center">
            Carrito de Compras
         </th>
      </tr>
      <tr>
         <th>Marca</th>
         <th>Cantidad</th>
         <th>Opciones</th>
      </tr>
   </thead>
   <tbody>
      {% if request.session.cart.items %}
         {% for key, value in request.session.cart.items %}
            <tr class="text-center">
               <td>{{ value.name }}</td>
               <td>{{ value.quantity }}</td>
               <td>
                  <a href="{% url 'cart:add_procesador' value.product_id %}"
                     class="btn btn-sm btn-success">
                     +
                  </a>
                  <a href="{% url 'cart:decrement_procesador' value.product_id %}"
                     class="ml-2 btn-sm btn btn-danger">
                     -
                  </a>
                  <hr>
                  Total {{ value.price|multiply:value.quantity|money_format:"$" }}
               </td>
            
            </tr>
         {% endfor %}
      
      {% else %}
         <tr>
            <td colspan="3">
               <div class="alert alert-danger text-center">
                  No tienes productos en el carrito
               </div>
            </td>
         </tr>
      {% endif %}
   </tbody>
   <tfoot>
      <tr>
         <td colspan="3">
            Total: {{ cart_total_amount|money_format:"$"}}
         </td>
      </tr>
   </tfoot>
</table>

EscPc/catalog/templates/cart/widget_ram.html
{% load cart_tags %}
<table class="table table-bordered">
   <thead>
      <tr>
         <th colspan="3" class="text-center">
            Carrito de Compras
         </th>
      </tr>
      <tr>
         <th>Marca</th>
         <th>Cantidad</th>
         <th>Opciones</th>
      </tr>
   </thead>
   <tbody>
      {% if request.session.cart.items %}
         {% for key, value in request.session.cart.items %}
            <tr class="text-center">
               <td>{{ value.name }}</td>
               <td>{{ value.quantity }}</td>
               <td>
                  {% block add_decrement %}
                  <a href="{% url 'cart:add_ram' value.product_id %}"
                     class="btn btn-sm btn-success">
                     +
                  </a>
                  <a href="{% url 'cart:decrement_ram' value.product_id %}"
                     class="ml-2 btn-sm btn btn-danger">
                     -
                  </a>
                  {% endblock %}
                  <hr>
                  Total {{ value.price|multiply:value.quantity|money_format:"$" }}
               </td>
            
            </tr>
         {% endfor %}
      
      {% else %}
         <tr>
            <td colspan="3">
               <div class="alert alert-danger text-center">
                  No tienes productos en el carrito
               </div>
            </td>
         </tr>
      {% endif %}
   </tbody>
   <tfoot>
      <tr>
         <td colspan="3">
            Total: {{ cart_total_amount|money_format:"$"}}
         </td>
      </tr>
   </tfoot>
</table>