EscPc/EscPc/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from EscPc.quickstart import views
from rest_framework import routers

#API
router = routers.DefaultRouter()
router.register(r'motherboard', views.PlacasMadreViewSet)
router.register(r'processor', views.ProcesadorViewSet)
router.register(r'gpu', views.GpuViewSet)
router.register(r'memorias-ram', views.RamViewSet)
router.register(r'users', views.UserViewSet)

urlpatterns = [
   path('admin/', admin.site.urls),
   path('', include('catalog.urls')),
   path('accounts/', include('django.contrib.auth.urls')),
   path('accounts/', include('sesion.urls')),
   path('cart/', include('cart.urls')),
   path('', include(router.urls)),
   path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

if settings.DEBUG:  
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

EscPc/cart/urls.py
from django.urls import path
from .views import *

app_name = "cart"

urlpatterns = [
   path('add_product/<int:product_id>/', add_product, name='add_product'),
   path('remove_product/<int:product_id>/', remove_product, name='remove_product'),
   path('decrement_product/<int:product_id>/', decrement_product, name='decrement_product'),
   path('clear/', clear_cart, name='clear_cart'),
   
   path('add_procesador/<int:product_id>/', add_procesador, name='add_procesador'),
   path('remove_procesador/<int:product_id>/', remove_procesador, name='remove_procesador'),
   path('decrement_procesador/<int:product_id>/', decrement_procesador, name='decrement_procesador'),
   path('clear_procesador/', clear_cart_procesador, name='clear_cart_procesador'),
   
   path('add_gpu/<int:product_id>/', add_gpu, name='add_gpu'),
   path('remove_gpu/<int:product_id>/', remove_gpu, name='remove_gpu'),
   path('decrement_gpu/<int:product_id>/', decrement_gpu, name='decrement_gpu'),
   path('clear_gpu/', clear_cart_gpu, name='clear_cart_gpu'),
   
   path('add_ram/<int:product_id>/', add_ram, name='add_ram'),
   path('remove_ram/<int:product_id>/', remove_ram, name='remove_ram'),
   path('decrement_ram/<int:product_id>/', decrement_ram, name='decrement_ram'),
   path('clear_ram/', clear_cart_ram, name='clear_cart_ram'),
   
]

EscPc/catalog/urls.py
#!/usr/bin/python3
from django.urls import path, include
from . import views

'''
      AQUI SE ENCUENTRAN LAS URLS DE LOS PRODUCTOS, TANTO LISTAS COMO
      LOS DEL CRUD, INDICANDO COMO PRIMER PARAMETRO EL URL QUE SE BUSCARA,
      COMO SEGUNDO, LA VISTA DE DONDE SE SACARA LA INFO Y COMO TERCER PARA-
      METRO, UN NOMBRE PARA PODER LLAMAR A LA URL DESDE OTRA PESTANNIA
   '''

urlpatterns = [
   
   #API
   
   
   # URL PRINCIPALES
   path('home', views.index, name="index"),
   path('placasmadres/', views.placamadre, name="placamadre"),
   path('procesadores/', views.procesador, name="procesador"),
   path('tarjetadevideo/', views.video, name="video"),
   path('ram/', views.rams, name="rams"),
   path('almacenamiento/', views.alma, name="alma"),
   path('fuenteDePoder/', views.fuente, name="fuente"),
   path('gabinetes/', views.gabo, name="gabo"),
   path('monitores/', views.moni, name="moni"),
   path('contacto/', views.contacto, name="contacto"),


   # URL PLACAS MADRE
   path('placasmadre/', views.PlacaListView.as_view(), name="placas"),
   path('placamadre/<int:pk>', views.PlacaDetailView.as_view(), name="placas-detail"),
   path('nueva-placa/', views.nueva_placa, name="nueva_placa"),
   path('modificar-placa/<id>/', views.modificar_placa, name="modificar_placa"),
   path('eliminar-placa/<id>/', views.eliminar_placa, name="eliminar_placa"),

   # URL PROCESADORES
   path('procesadore/', views.ProceListView.as_view(), name="procesadores"),
   path('procesador/<int:pk>', views.ProceDetailView.as_view(), name="procesadores-detail"),
   path('nuevo-procesador/', views.nuevo_procesador, name="nuevo_procesador"),
   path('modificar-procesador/<id>/', views.modicar_procesador, name="modificar_procesador"),
   path('eliminar-procesador/<id>/', views.eliminar_procesador, name="eliminar_procesador"),

   # URL GPU'S
   path('gpus/', views.GpuListView.as_view(), name="gpus"),
   path('gpu/<int:pk>', views.GpuDetailView.as_view(), name="gpu-detail"),
   path('nueva-gpu/', views.nuevo_gpu, name="nueva_gpu"),
   path('modificar-gpu/<id>/', views.modificar_gpu, name="modificar_gpu"),
   path('eliminar-gpu/<id>/', views.eliminar_gpu, name="eliminar_gpu"),

   # URL RAM
   path('rams/', views.RamListView.as_view(), name="memoriasram"),
   path('ram/<int:pk>', views.RamDetailView.as_view(), name="ram-detail"),
   path('nueva-ram/', views.nueva_ram, name="nueva_ram"),
   path('modificar-ram/<id>/', views.modificar_ram, name="modificar_ram"),
   path('eliminar-ram/<id>/', views.eliminar_ram, name="eliminar_ram"),

   # URL ALMACENAMIENTOS
   path('almacenamientos/', views.AlmacenamientoListView.as_view(), name="almacenamientos"),
   path('almacenamiento/<int:pk>', views.AlmacenamientoDetailView.as_view(), name="almacenamiento-detail"),
   path('nuevo-almacenamiento/', views.nuevo_almacenamiento, name="nuevo_almacenamiento"),
   path('modificar-almacenamiento/<id>/', views.modificar_almacenamiento, name="modificar_almacenamiento"),
   path('eliminar-almacenamiento/<id>/', views.eliminar_almacenamiento, name="eliminar_almacenamiento"),

   # URL FUENTES DE PODER
   path('fuentes/', views.FuentesPoderListView.as_view(), name="fuentes"),
   path('fuente-poder/<int:pk>', views.FuentesPoderDetailView.as_view(), name="fuente-detail"),
   path('nueva-fuente/', views.nueva_fuente, name="nueva_fuente"),
   path('modificar-fuente/<id>/', views.modificar_fuente, name="modificar_fuente"),
   path('eliminar-fuente/<id>/', views.eliminar_fuente, name="eliminar_fuente"),

   # URL GABINETE
   path('gabinetes/', views.GabineteListView.as_view(), name="gabinetes"),
   path('gabinete/<int:pk>', views.GabineteDetailView.as_view(), name="gabinete-detail"),
   path('nuevo-gabinete/', views.nuevo_gabinete, name="nuevo_gabinete"),
   path('modificar-gabinete/<id>/', views.modificar_gabinete, name="modificar_gabinete"),
   path('eliminar-gabinete/<id>/', views.eliminar_gabinete, name="eliminar_gabinete"),

   #URL MONITOR
   path('monitores/', views.MonitoreListView.as_view(), name="monitores"),
   path('monitor/<int:pk>', views.MonitoreDetailView.as_view(), name="monitor-detail"),
   path('nuevo-monitor/', views.nuevo_monitor, name="nuevo_monitor"),
   path('modificar-monitor/<id>', views.modificar_monitor, name="modificar_monitor"),
   path('eliminar-monitor/<id>', views.eliminar_monitor, name="eliminar_monitor"),
   
   
   
]

EscPc/catalog/models.py
#!/usr/bin/python3
from django.db import models
from django.urls import reverse
import uuid


class PlacasMadre(models.Model):
   marca = models.CharField(max_length=100,help_text='Marca del producto')
   modelo = models.CharField(max_length=100,help_text='Modelo del producto')

   CATALOGO_FORMATO_PLACAMADRE = (
      ('seleccione','Seleccione'),
      ('ATX','ATX'),
      ('Mini ITX','Mini ITX'),
      ('Micro ATX','Micro ATX'),
   )

   formato = models.CharField(max_length=10,choices=CATALOGO_FORMATO_PLACAMADRE,blank=False,default='s',help_text='Formato de la Placa Madre')

   CATALOGO_PLATAFORMA_PLACAMADRE = (
      ('seleccione','Seleccione'),
      ('AMD','AMD'),
      ('Intel','Intel')
   )

   plataforma = models.CharField(max_length=10,choices=CATALOGO_PLATAFORMA_PLACAMADRE,blank=False,default='se',help_text='Plataforma de la Placa Madre')
   stock = models.IntegerField(default=0,help_text='Stock del producto')
   imagen = models.ImageField(upload_to='placasmadres/',null=True)
   imagen_detail = models.ImageField(upload_to='placasmadres_detail/',null=True)
   precio = models.IntegerField(default=0)

   def __str__(self):
      return f'{self.marca},{self.modelo}'


class Procesadore(models.Model):
   CATALOGO_MARCA_PROCESADOR = (
      ('seleccione','Seleccione'),
      ('AMD','AMD'),
      ('Intel','Intel')
   )
   marca = models.CharField(max_length=10,choices=CATALOGO_MARCA_PROCESADOR,blank=False,default='s',help_text='Marca del producto')
   modelo = models.CharField(max_length=100,help_text='Modelo del producto')
   frecuencia = models.CharField(max_length=50,help_text='Frecuencia del producto')
   CATALOGO_SOCKET_PROCESADOR = (
      ('seleccione','Seleccione'),
      ('LGA 1151-v2','LGA 1151-v2'),
      ('AM4','AM4'),
      ('TR4','TR4')
   )
   socket = models.CharField(max_length=11,choices=CATALOGO_SOCKET_PROCESADOR,blank=False,default='s',help_text='Socket del producto')
   stock = models.IntegerField(default=0,help_text='Stock del producto')
   imagen = models.ImageField(upload_to='procesador/',null=True)
   imagen_detail = models.ImageField(upload_to='procesador_detail/',null=True)
   precio = models.IntegerField(default=0,help_text='Precio del producto')
   def __str__(self):
      return  f'{self.marca},{self.modelo}'

class Gpu(models.Model):
   
   marca = models.CharField(max_length=100,help_text='Marca del producto')
   modelo = models.CharField(max_length=100)

   CATALOGO_PLATAFORMA_GPU = (
      ('seleccione','Seleccione'),
      ('AMD','AMD'),
      ('Nvidia','Nvidia'),
   )

   plataforma = models.CharField(max_length=10, choices=CATALOGO_PLATAFORMA_GPU,blank=False,default='s',help_text='Plataforma del producto')
   memoria = models.CharField(max_length=100)
   frecuencia = models.CharField(max_length=100)
   stock = models.IntegerField(default=0)
   imagen = models.ImageField(upload_to='gpu/',null=True)
   imagen_detail = models.ImageField(upload_to='gpu_detail/', null=True)
   precio = models.IntegerField(default=0)

   def __str__(self):
      return  self.modelo

class Ram(models.Model):
   
   marca = models.CharField(max_length=100,help_text='Marca del producto')
   capacidad = models.CharField(max_length=100)

   CATALOGO_TIPO_RAM = (
      ('seleccione','Seleccione'),
      ('DDR3','DDR3'),
      ('DDR4','DDR4'),
   )

   tipo = models.CharField(max_length=10,choices=CATALOGO_TIPO_RAM,blank=False,default='se',help_text='Tipo de ram')
   frecuencia = models.CharField(max_length=50)

   CATALOGO_FORMATO_RAM = (
      ('seleccione','Seleccione'),
      ('DIMM','DIMM'),
      ('SO-DIMM','SO-DIMM')
   )

   formato = models.CharField(max_length=10,choices=CATALOGO_FORMATO_RAM,blank=False,default='s',help_text='Formato de la Ram')
   stock = models.IntegerField(default=0)
   imagen = models.ImageField(upload_to='ram/',null=True)
   imagen_detail = models.ImageField(upload_to='ram_detail/', null=True)
   precio = models.IntegerField(default=0)

   def __str__(self):
      return self.marca

class Almacenamiento(models.Model):
   marca = models.CharField(max_length=100,help_text='Marca del producto')
   modelo = models.CharField(max_length=50)
   capacidad = models.CharField(max_length=50)

   CATALOGO_FORMATO_ALMACENAMIENTO = (
      ('seleccione','Seleccione'),
      ('HDD','HDD'),
      ('M.2','M.2'),
      ('2.5"','2.5"'),
   )

   formato = models.CharField(max_length=10,choices=CATALOGO_FORMATO_ALMACENAMIENTO,blank=False,default='s',help_text='Formato del producto')
   bus = models.CharField(max_length=50)
   stock = models.IntegerField(default=0)
   imagen = models.ImageField(upload_to='almacenamiento/',null=True)
   imagen_detail = models.ImageField(upload_to='almacenamiento_detail/', null=True)
   precio = models.IntegerField(default=0)

   def __str__(self):
      return  self.modelo

class FuentesPoder(models.Model):
   marca = models.CharField(max_length=100,help_text='Marca del producto')
   potencia = models.CharField(max_length=50)

   CATALOGO_CERTIFICACION_FUENTE = (
      ('seleleccione','Seleccione'),
      ('80PLUS Gold','80PLUS Gold'),
      ('80PLUS Bronze','80PLUS Bronze'),
      ('Sin Certificacion','Sin Certificacion')
   )

   certificacion = models.CharField(max_length=20,choices=CATALOGO_CERTIFICACION_FUENTE,blank=False,default='sele',help_text='Certificacion del producto')

   CATALOGO_MODULAR_FUENTE = (
      ('se','Seleccione'),
      ('SI','SI'),
      ('NO','NO')
   )

   modular = models.CharField(max_length=2,choices=CATALOGO_MODULAR_FUENTE,blank=False,default='se')
   stock = models.IntegerField(default=0)
   imagen = models.ImageField(upload_to='fuentedepoder/',null=True)
   imagen_detail = models.ImageField(upload_to='fuentedepoder_detail/', null=True)
   precio = models.IntegerField(default=0)

   def __str__(self):
      return self.marca


class Gabinete(models.Model):

   marca = models.CharField(max_length=100,help_text='Marca del producto')
   modelo = models.CharField(max_length=50)

   CATALOGO_FUENTE_GABINETE = (
      ('seleccione','Seleccione'),
      ('No posee','No posee'),
      ('Si posee','Si posee')
   )

   fuente_gabinete = models.CharField(max_length=10,choices=CATALOGO_FUENTE_GABINETE,blank=False,default='se',help_text='Posee o no posee fuente de poder dentro del gabinete')

   CATALOGO_PANEL_GABIENTE = (
      ('seleccione','Seleccione'),
      ('Vidrio Templado','Vidrio Templado'),
      ('Panel Acrilico','Panel Acrilico')
   )
   panel = models.CharField(max_length=20,choices=CATALOGO_PANEL_GABIENTE,blank=False,default='s',help_text='Tipo de panel del gabinete')
   stock = models.IntegerField(default=0)
   imagen = models.ImageField(upload_to='gabinete/',null=True)
   imagen_detail = models.ImageField(upload_to='gabinete_detail/', null=True)
   precio = models.IntegerField(default=0)

   def __str__(self):
      return self.modelo

class Monitore(models.Model):
   marca = models.CharField(max_length=100,help_text='Marca del producto')
   modelo = models.CharField(max_length=50)

   CATALOGO_PULGADAS_MONITOR = (
      ('seleccione','Seleccione'),
      ('23.0"','23.0"'),
      ('24.0"','24.0"'),
      ('25.0"','25.0"'),
      ('26.0"','26.0"'),
      ('27.0"','27.0"')
   )

   pulgadas = models.CharField(max_length=10,choices=CATALOGO_PULGADAS_MONITOR,blank=False,default='sele',help_text='Pulgadas del monitor')
   resolucion = models.CharField(max_length=50)

   CATALOGO_TIEMPO_MONITOR = (
      ('seleccione','Seleccione'),
      ('1 ms','1 ms'),
      ('2 ms','2 ms'),
      ('3 ms','3 ms'),
      ('4 ms','4 ms'),
   )

   tiempo_respuesta = models.CharField(max_length=10,choices=CATALOGO_TIEMPO_MONITOR,blank=False,default='s',help_text='Tiempo de respuesta del monitor')

   CATALOGO_TASA_MONITOR = (
      ('seleccione','Seleccione'),
      ('120 Hz','120 Hz'),
      ('144 Hz','144 Hz'),
      ('165 Hz','165 Hz')
   )

   tasa_refresco = models.CharField(max_length=10,choices=CATALOGO_TASA_MONITOR,blank=False,default='sel',help_text='Tasa de refresco del monitor')
   stock = models.IntegerField(default=0)
   imagen = models.ImageField(upload_to='monitor/',null=True)
   imagen_detail = models.ImageField(upload_to='monitor_detail/', null=True)
   precio = models.IntegerField(default=0)

   def __str__(self):
      return self.modelo

opciones_consultas = [
   [0,"consulta"],
   [1,"sugerencia"],
   [2,"reclamo"]
]

class Contacto(models.Model):
   nombre = models.CharField(max_length=50)
   apellido = models.CharField(max_length=50)
   email = models.EmailField()
   tipo_consulta = models.IntegerField(choices=opciones_consultas)
   mensaje = models.TextField()

   def __str__(self):
      return self.email
   

EscPc/catalog/forms.py
#!/usr/bin/python3
from django import forms
from django.forms import ModelForm
from .models import PlacasMadre, Procesadore, Gpu, Ram, Almacenamiento, FuentesPoder, Gabinete, Monitore, Contacto


'''
   AQUI SE ENCUENTRAN LOS FORMULARIOS QUE SE OCUPARAN, EN ESTE CASO ESTAMOS 
   EXTRAYENDO TODOS LOS CAMPOS DE CADA MODELO RESPECTIVAMENTE
'''


class PlacaForm(ModelForm):
   class Meta:
      model = PlacasMadre
      fields = '__all__'

class ProceForm(ModelForm):

   class Meta:
      model = Procesadore
      fields = '__all__'

class GpuForm(ModelForm):

   class Meta:
      model = Gpu
      fields = '__all__'

class RamForm(ModelForm):

   class Meta:
      model = Ram
      fields = '__all__'

class AlmacenamientoForm(ModelForm):

   class Meta:
      model = Almacenamiento
      fields = '__all__'

class FuentesPoderForm(ModelForm):

   class Meta:
      model = FuentesPoder
      fields = '__all__'

class GabineteForm(ModelForm):

   class Meta:
      model = Gabinete
      fields = '__all__'

class MonitoreForm(ModelForm):

   class Meta:
      model = Monitore
      fields = '__all__'

class ContactoForm(ModelForm):
   
   class Meta:
      model = Contacto
      fields = '__all__'
      

EscPc/catalog/templates/almacenamiento.html
{% extends "base_generic.html" %}

{% block title %}Almacenamiento{% endblock %}

{% block content %}

<body style="background-color: #f8f8f8;">
   <section class="jumbotron text-center">
      <style>
         section {
               background-image: url("/static/fotos/bannerProductos.jpg");
         }
      </style>
      <div class="container-fluid">
         <h1 style="font-size: 6vw; color: white;">
               Almacenamiento
         </h1>
      </div>
   </section>
   <!--Seguimiento-->
   <div class="container" id="seguimiento">
      <div class="col-md-5">
         <ol class="breadcrumb breadcrumb-extend">
               <li class="breadcrumb-item">
                  <a href="{% url 'index' %}">
                     Inicio
                  </a>
               </li>
               <li class="breadcrumb-item active">
                  Almacenamiento
               </li>
         </ol>
      </div>
   </div>
   {% if perms.app.view_almacenamiento %}
   <div class="my-2 my-lg-0" style="text-align: center;">
      <a class="btn btn-warning btn-sm" href="{% url 'almacenamientos' %}" 
            style="font-size: 20px;">
         Lista de Productos
      </a>
   </div>
   {% endif %}
   {% if productoAlmacenamiento %}
   <div class="album py-5">
      <div class="container">
         <div class="row">
               {% for a in productoAlmacenamiento %}
               <div class="col-md-4">
                  <div class="card mb-4 shadow-sm">
                     <a href="{% url 'almacenamiento-detail' a.id %}">
                           <img class="producto" src="{{ a.imagen.url }}" />
                     </a>
                     <div class="card-body">
                           <p class="card-text">
                              <b>
                                 Marca:
                              </b>
                              {{ a.marca }}
                              <br>
                              <b>
                                 Modelo:
                              </b>
                              {{ a.modelo }}
                              <br>
                              <b>
                                 Capacidad:
                              </b>
                              {{ a.capacidad }}
                              <br>
                              <b>
                                 Formato:
                              </b>
                              {{ a.formato }}
                              <br>
                              <b>
                                 Bus:
                              </b>
                              {{ a.bus }}
                              <br>
                           </p>
                           <h3>
                              ${{ a.precio }}
                           </h3>
                           <div class="d-flex justify-content-between align-items-center">
                              <div class="btn-group">
                                 <button class="btn btn-sm btn-outline-secondary" type="button">
                                       Detalles
                                 </button>
                                 <button class="btn btn-sm btn-outline-secondary" type="button">
                                       Agregar
                                 </button>
                              </div>
                              <small class="text-muted ml-2">
                                 stock:
                                 <b>
                                       {{ a.stock }}
                                 </b>
                              </small>
                           </div>
                     </div>
                  </div>
               </div>
               {% endfor %}
         </div>
      </div>
   </div>
   {% else %}
   <p>
      No hay productos
   </p>
   {% endif %}
</body>
{% endblock %}

EscPc/catalog/templates/ram.html
{% extends "base_generic.html" %}
{% load cart_tags %}
{% block title %}Ram{% endblock %}
{% block content %}

<body style="background-color: #f8f8f8;">
   <section class="jumbotron text-center">
      <style>
         section {
               background-image: url("/static/fotos/bannerProductos.jpg");
         }
      </style>
      <div class="container-fluid">
         <h1 style="font-size: 6vw; color: white;">
            Ram
         </h1>
      </div>
   </section>

   <!--Seguimiento-->
   <div id="seguimiento" class="container">
      <div class="col-md-2">
         <ol class="breadcrumb breadcrumb-extend">
               <li class="breadcrumb-item">
                  <a href="{% url 'index' %}">
                     Inicio
                  </a>
               </li>
               <li class="breadcrumb-item active">
                  Ram
               </li>
         </ol>
      </div>
   </div>

   {% if perms.app.view_ram %}
   <div class="my-2 my-lg-0" style="text-align: center;">
      <a class="btn btn-warning btn-sm" href="{% url 'memoriasram' %}" style="font-size: 20px;">
         Lista de Productos
      </a>
   {% endif %}
   {% if user.is_authenticated %}
      <div class="col-2 float-right">
         {% include "cart/widget_ram.html" %}
      </div>
   {% else %}
      <p style="font-size: 25px;" class="text-center">
         Para poder agregar al carrito
         debes <a href="{% url 'registro' %}">registrarte</a>
         o <a href="{% url 'login' %}">Iniciar Sesion</a> 
      </p>
   {% endif %}
   </div>

   <div class="album py-5">
      <div class="container">
         {% if productoRam %}
         <div class="row">
            {% for product in productoRam %}
            <div class="col-md-4">
               <div class="card mb-4 shadow-sm">
                  <a href="{% url 'ram-detail' product.id %}">
                     <img class="producto" src="{{ product.imagen.url }}">
                  </a>
                  <div class="card-body">
                     <p class="card-text">
                        <b>Marca:</b> {{ product.marca}} <br>
                        <b>Capacidad:</b> {{ product.capacidad }} <br>
                        <b>Tipo:</b> {{ product.tipo }} <br>
                        <b>Frecuencia:</b> {{ product.frecuencia }} <br>
                        <b>Formato:</b> {{ product.formato}} <br>
                     </p>
                     <h3>${{ product.precio }}</h3>
                     <small class="text-muted ml-2">
                        stock:<b>{{ product.stock }}</b>
                     </small>
                  </div>
                  <div class="card-footer text-center mb-3 btn-group">
                     <a href="{% url 'ram-detail' product.id %}"
                           class="btn btn-sm btn-info">
                        Detalles
                     </a>

                     {% if user.is_authenticated %}
                        <a href="{% url 'cart:add_ram' product.id %}"
                              class="btn btn-sm btn-success">
                           Agregar a carrito
                        </a>
                     {% endif %}
                  </div>
               </div>
            </div>
            {% endfor %}
      </div>
      {% else %}
         <p>
            No hay productos
         </p>
      {% endif %}    
      </div>
   </div>
</body>
{% endblock %}

EscPc/catalog/templates/tarjetadevideo.html
{% extends "base_generic.html" %}

{% block title %}Tarjetas de Video{% endblock %}

{% block content %}

<body style="background-color: #f8f8f8;">
   <section class="jumbotron text-center">
      <style>
         section {
               background-image: url("/static/fotos/bannerProductos.jpg");
         }
      </style>
      <div class="container-fluid">
         <h1 style="font-size: 6vw; color: white;">
               Tarjetas de Video
         </h1>
      </div>
   </section>
   <!--Seguimiento-->
   <div class="container" id="seguimiento">
      <div class="col-md-3">
         <ol class="breadcrumb breadcrumb-extend">
               <li class="breadcrumb-item">
                  <a href="{% url 'index' %}">
                     Inicio
                  </a>
               </li>
               <li class="breadcrumb-item active">
                  Tarjetas de Video
               </li>
         </ol>
      </div>
   </div>
   {% if perms.app.view_gpu %}
   <div class="my-2 my-lg-0" style="text-align: center;">
      <a class="btn btn-warning btn-sm" href="{% url 'gpus' %}" style="font-size: 20px;">
         Lista de Productos
      </a>
   {% endif %}
   {% if user.is_authenticated %}
   <div class="col-2 ml-5 float-right">
      {% include "cart/widget_gpu.html" %}
   </div>
   {% else %}
      <p style="font-size: 25px;" class="text-center">
         Para poder agregar al carrito
         debes <a href="{% url 'registro' %}">registrarte</a>
         o <a href="{% url 'login' %}">Iniciar Sesion</a> 
      </p>
   {% endif %}
   </div>



   <div class="album py-5">
      <div class="container">
         {% if productoGpu %}
         <div class="row">
            {% for product in productoGpu %}
            <div class=" col-md-4">
               <div class="card mb-4 shadow-sm">
                  <a href="{% url 'gpu-detail' product.id %}">
                        <img class="producto" src="{{ product.imagen.url }}" />
                  </a>
                  <div class="card-body">
                     <p class="card-text">
                        <b>
                           Marca:
                        </b>
                        {{ product.marca }}
                        <br>
                        <b>
                           Modelo:
                        </b>
                        {{ product.modelo }}
                        <br>
                        <b>
                           Plataforma:
                        </b>
                        {{ product.plataforma }}
                        <br>
                        <b>
                           Memoria:
                        </b>
                        {{ product.memoria }}
                        <br>
                        <b>
                           Frecuencia:
                        </b>
                        {{ product.frecuencia }}
                     </p>
                     <h3>
                        ${{ product.precio }}
                     </h3>
                     <small class="text-muted ml-2">
                        stock:
                        <b>
                              {{ product.stock }}
                        </b>
                     </small>
                  </div>
                  <div class="card-footer text-center mb-3 btn-group">
                     <a href="{% url 'gpu-detail' product.id %}"
                           class="btn btn-sm btn-info">
                        Detalles
                     </a>
                     {% if user.is_authenticated %}
                     <a href="{% url 'cart:add_gpu' product.id %}"
                           class="btn btn-sm btn-success">
                        Agregar a carrito
                     </a>
                     {% endif %}
                  </div>
               </div>
            </div>
            {% endfor %}
         </div>
         {% else %}
            <p>
               No hay productos
            </p>
         {% endif %}
      </div>
   </div>

</body>
{% endblock %}